# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# Images need to be in `fromdesigner_dir` or need the path!!!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 341, 371))
        self.photo.setFrameShape(QtWidgets.QFrame.Box)
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("DSC00384.JPG"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.button_pic1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_pic1.setGeometry(QtCore.QRect(20, 400, 75, 23))
        self.button_pic1.setObjectName("button_pic1")
        self.button_pic2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_pic2.setGeometry(QtCore.QRect(270, 400, 75, 23))
        self.button_pic2.setObjectName("button_pic2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# Custom
# -----------------------------------------------------------------------------------------
#
        self.button_pic1.clicked.connect(self.show_pic1)
        self.button_pic2.clicked.connect(self.show_pic2)
#
# -----------------------------------------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_pic1.setText(_translate("MainWindow", "pic1"))
        self.button_pic2.setText(_translate("MainWindow", "pic2"))

# Custom methods
# -----------------------------------------------------------------------------------------
#
    def show_pic1(self):
        self.photo.setPixmap(QtGui.QPixmap("DSC00384.JPG"))

        # message box
        msg = QMessageBox()
        msg.setWindowTitle('changed pic')
        msg.setText('You changed it')
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Cancel | QMessageBox.Retry)
        msg.setDefaultButton(QMessageBox.Retry)
        msg.setInformativeText("Information")
        msg.setDetailedText("Detailed text")
        x = msg.exec_()

    def show_pic2(self):
        self.photo.setPixmap(QtGui.QPixmap("DSC00381.JPG"))
#
# -----------------------------------------------------------------------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
