"""
Here we invoke a lambda function named `ReportGenerator` in AWS.
"""
import os
import json

from dotenv import load_dotenv
import boto3


load_dotenv()


access_key_id=os.getenv("AWS_ACCESS_KEY_ID", ""),
secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY", ""),
region=os.getenv("AWS_REGION_NAME", "eu-central-1")
s3_bucket_name=os.getenv("S3_BUCKET_NAME", "")


lambda_client = boto3.client('lambda',
    region_name=region,
)


def invoke_report_generator():
    """Invoke your ReportGenerator Lambda"""

    payload = {
        'trigger_source': 'python_script',
        'custom_data': {
            'user': 'pycharm_user',
            'purpose': 'test_lambda_invocation'
        }
    }

    try:
        print(" Invoking ReportGenerator Lambda...")

        # Invoke the Lambda
        response = lambda_client.invoke(
            FunctionName='ReportGenerator',
            InvocationType='RequestResponse',  # Wait for response
            Payload=json.dumps(payload)
        )

        response_payload = json.loads(response['Payload'].read())

        print(" Lambda invoked successfully!")
        print(f"   Status: {response_payload.get('status', 'unknown')}")
        print(f"   Message: {response_payload.get('message', 'No message')}")

        if 'file_name' in response_payload:
            print(f"   File to be created: {response_payload['file_name']}")

        print(f"\n Response details:")
        print(f"   Status Code: {response['StatusCode']}")
        print(f"   Executed Version: {response.get('ExecutedVersion', '$LATEST')}")

        return response_payload

    except Exception as e:
        print(f" Error invoking Lambda: {str(e)}")
        return None


# Run it
if __name__ == "__main__":
    result = invoke_report_generator()

    if result and result.get('status') == 'success':
        print("\n Success! Check your S3 bucket in a few seconds:")


# ----------------------------------------------------------------------------------------
# ReportGenerator Code
# ----------------------------------------------------------------------------------------
'''
import json
import boto3
from datetime import datetime

lambda_client = boto3.client('lambda')

def lambda_handler(event, context):
    print("ReportGenerator: Starting...")
    
    # 1. Generate a simple report
    report_content = f"""
    ============ REPORT ============
    Generated by: ReportGenerator Lambda
    Timestamp: {datetime.now().isoformat()}
    
    Hello from AWS Lambda!
    
    This report was generated by Lambda A (ReportGenerator)
    and will be saved to S3 by Lambda B (S3Uploader).
    
    Event received: {json.dumps(event)}
    ================================
    """
    
    # 2. Prepare data for S3Uploader
    s3_payload = {
        'bucket_name': 'mybucket-danielevgenievzorov',
        'file_name': f'reports/report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.txt',
        'file_content': report_content,
        'source': 'ReportGenerator',
        'generated_at': datetime.now().isoformat()
    }
    
    print(f"ReportGenerator: Calling S3Uploader with payload: {json.dumps(s3_payload, indent=2)}")
    
    try:
        # 3. Invoke S3Uploader Lambda
        response = lambda_client.invoke(
            FunctionName='S3Uploader',
            InvocationType='Event',  # Async - don't wait for response
            Payload=json.dumps(s3_payload)
        )
        
        print(f"ReportGenerator: Successfully invoked S3Uploader")
        print(f"ReportGenerator: Response status: {response['StatusCode']}")
        
        return {
            'status': 'success',
            'message': 'Report generation started',
            's3_upload_triggered': True,
            'file_name': s3_payload['file_name']
        }
        
    except Exception as e:
        print(f"ReportGenerator: ERROR - {str(e)}")
        return {
            'status': 'error',
            'error': str(e)
        }
'''

# ----------------------------------------------------------------------------------------
# S3Uploader Code
# ----------------------------------------------------------------------------------------
'''
import json
import boto3

s3_client = boto3.client('s3')

def lambda_handler(event, context):
    print("S3Uploader: Received event:", json.dumps(event, indent=2))
    
    try:
        # Get data from the event
        bucket_name = event.get('bucket_name', 'mybucket-danielevgenievzorov')
        file_name = event['file_name']
        file_content = event['file_content']
        
        # Upload to S3
        response = s3_client.put_object(
            Bucket=bucket_name,
            Key=file_name,
            Body=file_content,
            ContentType='text/plain'
        )
        
        print(f"S3Uploader: Successfully uploaded to s3://{bucket_name}/{file_name}")
        print(f"S3Uploader: ETag: {response['ETag']}")
        
        return {
            'status': 'success',
            'message': f'File uploaded to S3: {file_name}',
            's3_location': f's3://{bucket_name}/{file_name}',
            'etag': response['ETag']
        }
        
    except Exception as e:
        print(f"S3Uploader: ERROR - {str(e)}")
        return {
            'status': 'error',
            'error': str(e)
        }
'''
