apiVersion: batch/v1
kind: Job
metadata:
    name: pi-calculation
spec:
    template:
        spec:
            containers:
            - name: pi
              image: ubuntu
              command: ["bash", "-c", "echo 'scale=1000; 4*a(1)' | bc -l"]
            restartPolicy: Never
