apiVersion: v1                        # API version
kind: Pod                             # Define a Pod resource
metadata:                             # Metadata about the pod
  name: first-service-pod             # Name of the pod
  labels:                             # Labels to identify the pod
    app: first-service                # Application label
    type: backend                     # Type label
spec:                                 # Specification of the pod
  containers:                         # List of containers in the pod
    - name: web-container             # Name of the first container
      image: my-web-app:latest        # Docker image for the web application
      ports:                          # Ports to expose
        - containerPort: 8000         # Expose port 8000
      env:                            # Environment variables
        - name: DOCKER
          value: "True"
        - name: DATABASE_URL
          value: "postgresql://postgres_user:password@db/ohmi_audit_db"
        - name: DEBUG
          value: "True"
      volumeMounts:                   # Volume mounts for persistent storage
        - name: media-volume
          mountPath: /app/media_files
      readinessProbe:                 # Readiness probe configuration
        httpGet: