apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
data:
  # you must specify base64 encoded values here, by
  # `[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("production"))`
  APP_ENV: cHJvZHVjdGlvbg==
  APP_DEBUG: ZmFsc2U=
  APP_VERSION: MS4wLjA=
